version: '3'
services:
  azure-vote-back:
    image: mcr.microsoft.com/cbl-mariner/base/redis:6.2
    container_name: azure-vote-back
    command: ["redis-server", "--protected-mode", "no"]
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front:v1
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
